# Generated by Django 5.0.6 on 2024-07-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('agente', 'Agente'), ('admin', 'Admin')], default='usuario', max_length=20),
        ),
    ]
