# Generated by Django 5.0.6 on 2024-07-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
    ]
